var publicHolidayList = {
    "fields": [{ "id": "_id", "type": "int" }, { "id": "ID", "type": "text" }, { "id": "Date", "type": "text" }, { "id": "Holiday Name", "type": "text" }, { "id": "Information", "type": "text" }, { "id": "More Information", "type": "text" }, { "id": "Jurisdiction", "type": "text" }],
    "records": [
      [330, "333", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [331, "334", "20240126", "Australia Day", "Always celebrated on 26 January", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [332, "335", "20240311", "Canberra Day", "Held on the second Monday of March each year in Canberra to celebrate the naming ceremony of Australia's capital which took place on 12 March 1913.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [333, "336", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [334, "337", "20240330", "Easter Saturday - the day after Good Friday", "Easter Saturday is between Good Friday and Easter Sunday in Australia.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [335, "338", "20240331", "Easter Sunday", "Public Holiday as part of Easter.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [336, "339", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [337, "340", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [338, "341", "20240527", "Reconciliation Day", "Takes place on the first Monday on or after 27 May each year the anniversary of the 1967 referendum", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [339, "342", "20240610", "Sovereign's Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [340, "343", "20241007", "Labour Day", "Always on a Monday creating a long weekend. It celebrates the eight-hour working day a victory for workers in the mid-late 19th century.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [341, "344", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [342, "345", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://www.cmtedd.act.gov.au/communication/holidays", "act"],
      [343, "346", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [344, "347", "20240126", "Australia Day", "Always celebrated on 26 January", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [345, "348", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [346, "349", "20240330", "Easter Saturday", "Easter Saturday is between Good Friday and Easter Sunday in Australia.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [347, "350", "20240331", "Easter Sunday", "Public Holiday as part of Easter.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [348, "351", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [349, "352", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [350, "353", "20240610", "King's Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [351, "354", "20240805", "Bank Holiday", "Applies to banks and certain financial institutions, per the Retail Trading Act 2008", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [352, "355", "20241007", "Labour Day", "Always on a Monday creating a long weekend. It celebrates the eight-hour working day a victory for workers in the mid-late 19th century.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [353, "356", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [354, "357", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://www.nsw.gov.au/about-nsw/public-holidays", "nsw"],
      [355, "358", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://nt.gov.au/nt-public-holidays", "nt"],
      [356, "359", "20240126", "Australia Day", "Always celebrated on 26 January", "https://nt.gov.au/nt-public-holidays", "nt"],
      [357, "360", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [358, "361", "20240330", "Easter Saturday", "Easter Saturday is between Good Friday and Easter Sunday in Australia.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [359, "362", "20240331", "Easter Sunday", "Public Holiday as part of Easter.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [360, "363", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [361, "364", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [362, "365", "20240506", "May Day", "Always on a Monday, creating a long weekend. It celebrates the eight-hour working day, a victory for workers in the mid-late 19th century.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [363, "366", "20240610", "King's Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [364, "367", "20240805", "Picnic Day", "Observed on the first Monday of August each year and is clebrated with a horse race, railway picnic and other social outings", "https://nt.gov.au/nt-public-holidays", "nt"],
      [365, "368", "20241224", "Christmas Eve", "Part-day holiday 7pm to midnight", "https://nt.gov.au/nt-public-holidays", "nt"],
      [366, "369", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [367, "370", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://nt.gov.au/nt-public-holidays", "nt"],
      [368, "371", "20241231", "New Year's Eve", "Part-day holiday 7pm to midnight", "https://nt.gov.au/nt-public-holidays", "nt"],
      [369, "372", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [370, "373", "20240126", "Australia Day", "Always celebrated on 26 January", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [371, "374", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [372, "375", "20240330", "Easter Saturday", "Easter Saturday is between Good Friday and Easter Sunday in Australia.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [373, "376", "20240331", "Easter Sunday", "Public Holiday as part of Easter.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [374, "377", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [375, "378", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [376, "379", "20240506", "Labour Day", "Always on a Monday creating a long weekend. It celebrates the eight-hour working day a victory for workers in the mid-late 19th century.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [377, "380", "20240814", "Royal Queensland Show (Brisbane only)", "The Royal National Agricultural (RNA) Show Day (Brisbane only) is held on the Wednesday during the RNA Show period. The RNA Show commences on the first Friday in August, unless the first Friday is prior to 5 August, then it commences on the second Friday of August.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [378, "381", "20241007", "King’s Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [379, "382", "20241224", "Christmas Eve", "From 2019, the Holidays Act 1983 provides for a part-day public holiday from 6pm to midnight on Christmas Eve", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [380, "383", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [381, "384", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://www.qld.gov.au/recreation/travel/holidays/public", "qld"],
      [382, "385", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [383, "386", "20240126", "Australia Day", "Always celebrated on 26 January", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [384, "387", "20240311", "Adelaide Cup Day (subject to Proclamation)", "The Holidays Act 1910 provides for the third Monday in May to be a public holiday, through the issuing of a special Proclamation by the Governor.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [385, "388", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [386, "389", "20240330", "Easter Saturday", "Easter Saturday is between Good Friday and Easter Sunday in Australia.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [387, "391", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [388, "392", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [389, "393", "20240610", "King’s Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [390, "394", "20241007", "Labour Day", "Always on a Monday creating a long weekend. It celebrates the eight-hour working day a victory for workers in the mid-late 19th century.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [391, "395", "20241224", "Christmas Eve", "7pm to midnight", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [392, "396", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [393, "397", "20241226", "Boxing Day / Proclamation Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [394, "398", "20241231", "New Year's Eve", "7pm to midnight", "https://www.safework.sa.gov.au/resources/public-holidays", "sa"],
      [395, "399", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [396, "400", "20240126", "Australia Day", "Always celebrated on 26 January", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [397, "401", "20240311", "Eight Hours Day", "Always on a Monday, creating a long weekend. It celebrates the eight-hour working day, a victory for workers in the mid-late 19th century.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [398, "402", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [399, "405", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [400, "406", "20240402", "Easter Tuesday", "Public Holiday currently observed by certain awards/agreements and the State Public Service", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [401, "407", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [402, "408", "20240610", "King's Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [403, "409", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [404, "410", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays", "tas"],
      [405, "411", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [406, "412", "20240126", "Australia Day", "Always celebrated on 26 January", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [407, "413", "20240311", "Labour Day", "Always on a Monday, creating a long weekend. It celebrates the eight-hour working day, a victory for workers in the mid-late 19th century.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [408, "414", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [409, "415", "20240330", "Easter Saturday", "Easter Saturday is between Good Friday and Easter Sunday in Australia.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [410, "416", "20240331", "Easter Sunday", "Public Holiday as part of Easter.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [411, "417", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [412, "418", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [413, "419", "20240610", "King's Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [414, "420", "20240927", "Friday before the AFL Grand Final", "Friday before the AFL Grand Final - Subject to AFL schedule", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [415, "421", "20241105", "Melbourne Cup", "All of Victoria unless alternate local holiday has been arranged by non-metro council.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [416, "422", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [417, "423", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://business.vic.gov.au/business-information/public-holidays", "vic"],
      [418, "424", "20240101", "New Year's Day", "New Year's Day is the first day of the calendar year and is celebrated each January 1st", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [419, "425", "20240126", "Australia Day", "Always celebrated on 26 January", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [420, "426", "20240304", "Labour Day", "Always on a Monday, creating a long weekend. It celebrates the eight-hour working day, a victory for workers in the mid-late 19th century.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [421, "427", "20240329", "Good Friday", "Easter is celebrated with Good Friday and Easter Monday creating a 4 day long weekend.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [422, "428", "20240331", "Easter Sunday", "Public Holiday as part of Easter.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [423, "429", "20240401", "Easter Monday", "Public Holiday as part of Easter.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [424, "430", "20240425", "Anzac Day", "Celebrated on the 25 April each year.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [425, "431", "20240603", "Western Australia Day", "Held on the first Monday in June each year and is a state holiday only.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [426, "432", "20240923", "King's Birthday", "Celebrated on second Monday in June except in Western Australia and Queensland.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [427, "433", "20241225", "Christmas Day ", "Christmas Day is an annual holiday which celebrates the birth of Jesus Christ over 2000 years ago.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"],
      [428, "434", "20241226", "Boxing Day", "Boxing Day occurs the day after Christmas. Sydney-to-Hobart yacht race and Boxing Day Test Match (Cricket) start on this day.", "https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia", "wa"]
    ]
  };
